<img src="https://ga-curriculum.github.io/universal-resources-internal/ga-logos/ga-red-cog-72x72.png" alt="" style="float: left; margin: 20px 20px 0 0; height: 55px">

# EDA Walkthrough

_Authors: Kiefer Katovich (SF), David Yerrington (SF), Riley Dallas (AUS)_

---

The dataset for today's lesson (`Heart.csv`) comes from the book, [An Introduction to Statistical Learning (ISLR)](http://faculty.marshall.usc.edu/gareth-james/ISL/). It's comprised of diagnostic measurements for 303 patients to determine whether or not they have heart disease (the `AHD` column).

Though in many if not most cases the EDA procedure will be considerably more involved, this should give you an idea of the basic workflow a data scientist would use when working with a new dataset.

### Learning Objectives

- Quickly describe a dataset, including data types, missing values and basic descriptive statistics
- Rename columns (series) in a DataFrame
- Visualize data distributions with box plots
- Calculate and visualize correlation

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Load the data

---

Import the CSV into a pandas DataFrame.

In [29]:
file_path = './datasets/Heart.csv'

In [30]:
df = pd.read_csv(file_path)

In [31]:
df.head()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,0
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,1
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,1
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,0
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,0

## Describe the basic format of the data and the columns

---

Use the `.head()` method (and optionally pass in an integer for the number of rows you want to see) to get a glimpse of your dataset. This is a good initial step to get a feel for what is in the CSV and what problems may be present.

The `.dtypes` attribute tells you the data type for each of your columns.

In [32]:
# Print out the first 8 rows:
df.head(2)

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,0
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,1

In [33]:
# Look at the dtypes of the columns:
df.dtypes

Unnamed: 0      int64
Age            object
Sex             int64
ChestPain      object
RestBP          int64
Chol            int64
Fbs             int64
RestECG         int64
MaxHR           int64
ExAng           int64
Oldpeak       float64
Slope           int64
Ca            float64
Thal           object
AHD             int64
dtype: object

## Drop unwanted columns

---

It looks like `Unnamed: 0` is an index. This is redundant, since `pandas` automatically creates an index for us (the bold numbers to the left of the DataFrame).

The `.drop()` method can be used to get rid of a column like so:

```python
df.drop(columns=['list', 'columns', 'to', 'drop'], inplace=True)
```

The `inplace=True` parameter makes our change permanent.

In [34]:
# print out the index object and the first 20 items in the DataFrame's index 
# to see that we have these row numbers already:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [35]:
df.head()

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,0
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,1
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,1
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,0
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,0

In [36]:
# Remove the unneccesary column:

## Clean corrupted column

---

From the previous step, we noticed the `Age` column was interpreted as a string, even though the values are integers.

It is pretty common to have numeric columns represented as strings in your data if some of the observations are corrupted. It is important to always check the data types of your columns.

**What is causing the `Age` column to be encoded as a string?**

In [37]:
df['Age'].value_counts()

58    17
57    17
54    16
59    13
52    12
51    12
60    12
44    11
56    11
41    10
64    10
62     9
?      9
67     9
55     8
42     8
43     8
61     8
45     8
63     8
53     8
65     8
48     7
66     7
46     7
47     5
50     5
49     5
39     4
70     4
35     4
68     4
69     3
40     3
71     3
38     2
37     2
34     2
77     1
29     1
74     1
76     1
Name: Age, dtype: int64

In [38]:
df[~df['Age'].str.isdigit()]

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
26,?,0,nonanginal,120,340,0,0,172,0,0.0,1,0.0,normal,0
62,?,1,asymptomatic,128,216,0,2,131,1,2.2,2,3.0,reversable,1
92,?,1,nonanginal,130,231,0,0,146,0,1.8,2,3.0,reversable,0
121,?,0,asymptomatic,150,407,0,2,154,0,4.0,2,3.0,reversable,1
198,?,0,nontypical,120,244,0,0,162,0,1.1,1,0.0,normal,0
207,?,1,asymptomatic,144,200,0,2,126,1,0.9,2,0.0,reversable,1
214,?,1,asymptomatic,112,230,0,0,160,0,0.0,1,1.0,normal,1
249,?,1,nontypical,128,208,1,2,140,0,0.0,1,0.0,normal,0
274,?,1,typical,134,204,0,0,162,0,0.8,1,2.0,normal,1

In the cell below, replace all "?" cells with `np.nan`.

In [40]:
# Many options
df['Age'] = np.where(df['Age'] == '?', np.nan, df['Age']).astype(float)

In [41]:
df.dtypes

Age          float64
Sex            int64
ChestPain     object
RestBP         int64
Chol           int64
Fbs            int64
RestECG        int64
MaxHR          int64
ExAng          int64
Oldpeak      float64
Slope          int64
Ca           float64
Thal          object
AHD            int64
dtype: object

In [42]:
df['Age'].value_counts()

58.0    17
57.0    17
54.0    16
59.0    13
60.0    12
51.0    12
52.0    12
56.0    11
44.0    11
41.0    10
64.0    10
62.0     9
67.0     9
42.0     8
43.0     8
53.0     8
63.0     8
65.0     8
55.0     8
61.0     8
45.0     8
46.0     7
66.0     7
48.0     7
50.0     5
47.0     5
49.0     5
39.0     4
68.0     4
35.0     4
70.0     4
69.0     3
40.0     3
71.0     3
34.0     2
37.0     2
38.0     2
74.0     1
29.0     1
77.0     1
76.0     1
Name: Age, dtype: int64

## Determine how many observations are missing

---

Having replaced the question marks with `np.nan` values, we know that there are some missing observations for the `Age` column. 

When we start to build models with data, null values in observations are (almost) never allowed. It is important to always see how many observations are missing for each column.

We can count the null values for each column like so:

```python
df.isnull().sum()
```

The `.isnull()` method will convert the columns to `True` and `False` values.

The `.sum()` method will then sum these boolean columns, and the total number of null values per column will be returned.

In [45]:
df.isna().sum()

Age          9
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           4
Thal         2
AHD          0
dtype: int64

**Drop the null values.** 

In this case, lets keep it simple and just drop the rows from the dataset that contain null values. If a column has a ton of null values it often makes more sense to drop the column entirely instead of the rows with null values.

The `.dropna()` function will drop any rows that have _**ANY**_ null values for you.  Use this carefully as you could drop many more rows than expected.

In [46]:
# MAR = Missing because of a pattern (not ok to drop)
# MCAR = Missing because of no pattern (probably ok to drop)

In [48]:
df[df['Ca'].isna() | df['Thal'].isna()]

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
87,53.0,0,nonanginal,128,216,0,2,115,0,0.0,1,0.0,NaN,0
166,52.0,1,nonanginal,138,223,0,0,169,0,0.0,1,NaN,normal,0
192,43.0,1,asymptomatic,132,247,1,2,143,1,0.1,2,NaN,reversable,1
266,52.0,1,asymptomatic,128,204,1,0,156,1,1.0,2,0.0,NaN,1
287,58.0,1,nontypical,125,220,0,0,144,0,0.4,2,NaN,reversable,0
302,38.0,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,0

In [50]:
df.shape

(303, 14)

In [53]:
# DANGEROUS!! DON'T JUST USE THIS WILLY NILLY!!
# By default drops ALL rows with ANY missing values
df.dropna(subset=['Ca', 'Thal']).shape

(297, 14)

In [54]:
df.dropna(inplace=True)

In [55]:
df.shape

(288, 14)

In [56]:
df.head()

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63.0,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,0
1,67.0,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,1
2,67.0,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,1
3,37.0,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,0
4,41.0,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,0

In [57]:
df.describe()

,Age,Sex,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,AHD
count,288.000000,288.000000,288.000000,288.000000,288.000000,288.00000,288.000000,288.000000,288.000000,288.000000,288.000000,288.000000
mean,54.461806,0.677083,131.760417,247.163194,0.145833,1.00000,149.576389,0.329861,1.051042,1.607639,0.656250,0.458333
std,9.138039,0.468405,17.924393,51.425510,0.353553,0.99476,23.152601,0.470981,1.163528,0.620956,0.916304,0.499128
min,29.000000,0.000000,94.000000,126.000000,0.000000,0.00000,71.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,47.000000,0.000000,120.000000,211.750000,0.000000,0.00000,133.000000,0.000000,0.000000,1.000000,0.000000,0.000000
50%,56.000000,1.000000,130.000000,243.000000,0.000000,1.00000,152.500000,0.000000,0.800000,2.000000,0.000000,0.000000
75%,61.000000,1.000000,140.000000,276.250000,0.000000,2.00000,166.000000,1.000000,1.600000,2.000000,1.000000,1.000000
max,77.000000,1.000000,200.000000,564.000000,1.000000,2.00000,202.000000,1.000000,6.200000,3.000000,3.000000,1.000000

In [61]:
df.head(2)

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63.0,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,0
1,67.0,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,1

In [62]:
cat_cols = [
    'Sex',
    'ChestPain',
    'Fbs',
    'RestECG',
    'ExAng',
    'Slope',
    'Ca',
    'Thal',
    'AHD'
]

for col in cat_cols:
    print(f"COLUMN = {col}")
    print(df[col].value_counts())
    print('='*60)

COLUMNS = Sex
1    195
0     93
Name: Sex, dtype: int64
============================================================
COLUMNS = ChestPain
asymptomatic    138
nonanginal       81
nontypical       47
typical          22
Name: ChestPain, dtype: int64
============================================================
COLUMNS = Fbs
0    246
1     42
Name: Fbs, dtype: int64
============================================================
COLUMNS = RestECG
2    142
0    142
1      4
Name: RestECG, dtype: int64
============================================================
COLUMNS = ExAng
0    193
1     95
Name: ExAng, dtype: int64
============================================================
COLUMNS = Slope
1    134
2    133
3     21
Name: Slope, dtype: int64
============================================================
COLUMNS = Ca
0.0    170
1.0     64
2.0     37
3.0     17
Name: Ca, dtype: int64
============================================================
COLUMNS = Thal
normal        159
reversable    111
fixed          18
Name: Thal, dtype: int64
============================================================
COLUMNS = AHD
0    156
1    132
Name: AHD, dtype: int64
============================================================

In [58]:
df['ChestPain'].value_counts()

asymptomatic    138
nonanginal       81
nontypical       47
typical          22
Name: ChestPain, dtype: int64

In [60]:
df['Sex'].value_counts()

1    195
0     93
Name: Sex, dtype: int64

In [63]:
# DO NOT LOOK AT CORRELATIONS OF CATEGORICAL VARIABLES!!!!!!

# Rule for thee
# df.corr(numeric_only=True)

# not for me
df.corr()

,Age,Sex,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,AHD
Age,1.000000,-0.094471,0.291517,0.200144,0.130069,0.150640,-0.399860,0.105350,0.193581,0.161608,0.358584,0.233030
Sex,-0.094471,1.000000,-0.067347,-0.173120,0.032875,0.029912,-0.049927,0.137046,0.119853,0.030073,0.089553,0.277575
RestBP,0.291517,-0.067347,1.000000,0.129044,0.184773,0.139721,-0.043997,0.061811,0.182143,0.111736,0.094889,0.149796
Chol,0.200144,-0.173120,0.129044,1.000000,0.022258,0.170143,-0.012242,0.075597,0.016893,-0.013046,0.109374,0.084361
Fbs,0.130069,0.032875,0.184773,0.022258,1.000000,0.059442,-0.003494,0.003052,0.019111,0.055218,0.176791,0.014809
RestECG,0.150640,0.029912,0.139721,0.170143,0.059442,1.000000,-0.058548,0.066933,0.104160,0.124097,0.133791,0.161405
MaxHR,-0.399860,-0.049927,-0.043997,-0.012242,-0.003494,-0.058548,1.000000,-0.377610,-0.351614,-0.385075,-0.277720,-0.427872
ExAng,0.105350,0.137046,0.061811,0.075597,0.003052,0.066933,-0.377610,1.000000,0.294712,0.241546,0.158700,0.421805
Oldpeak,0.193581,0.119853,0.182143,0.016893,0.019111,0.104160,-0.351614,0.294712,1.000000,0.577109,0.272410,0.426353
Slope,0.161608,0.030073,0.111736,-0.013046,0.055218,0.124097,-0.385075,0.241546,0.577109,1.000000,0.098937,0.334919
Ca,0.358584,0.089553,0.094889,0.109374,0.176791,0.133791,-0.277720,0.158700,0.272410,0.098937,1.000000,0.467582
AHD,0.233030,0.277575,0.149796,0.084361,0.014809,0.161405,-0.427872,0.421805,0.426353,0.334919,0.467582,1.000000

### Extra Time Topic: Ternary Operator

In [64]:
# Binary operators:
1 + 1

# Unary operators:
-5

-5

In [66]:
# Ternary operators:
# np.where(cond, if_yes, if_no)
# =IF(cond, if_yes, if_no)
# cond ? if_yes : if_no

# Don't do this:
x = 5
if x > 3:
    choice = 'Yes'
else:
    choice = 'No'

In [67]:
# Do this instead:
choice = 'Yes' if x > 3 else 'No'

In [68]:
choice

'Yes'

## Make the column names more descriptive
---

One minor annoyance is that our column names are not at all intuitive. 

Let's rename them! 

To rename columns, use _dictionary substitution_ with `.rename()`. This is very useful if you only want to rename a few columns.

In [ ]:
# Dictionary Method
new_columns_dict = {
    'Age': 'age',
    'Sex': 'sex_male',
    'ChestPain': 'chest_pain',
    'RestBP': 'resting_blood_pressure',
    'Chol': 'cholesterol',
    'Fbs': 'fasting_blood_sugar',
    'RestECG': 'resting_ecg',
    'MaxHR': 'max_heart_rate',
    'ExAng': 'exercise_induced_angina',
    'Oldpeak': 'old_peak',
    'Slope': 'slope',
    'Ca': 'ca',
    'Thal': 'thallium_stress_test',
    'AHD': 'has_heart_disease',
}

## Describe the summary statistics for the columns
---

<img src="https://snag.gy/07JFa5.jpg" width="350">

---

The `.describe()` function gives summary statistics for each of your columns. What are some, if any, oddities you notice about the columns based on this output?

You can also use `.groupby()` + `.describe()` for cohort analysis

## Plot variables with potential outliers using boxplots.

---

Here we will use the seaborn package to plot boxplots of the variables we have identified as potentially having outliers.

Some notes on seaborn's boxplot keyword argument options:

    orient: can be 'v' or 'h' for vertical and horizontal, respectively
    fliersize: the size of the outlier points (pixels I think)
    linewidth: the width of line outlining the boxplot
    notch: show the confidence interval for the median (calculated by seaborn/plt.boxplot)
    saturation: saturate the colors to an extent

There are more keyword arguments available but those are most relevant for now.

_If you want to check out more, place your cursor in the `boxplot` argument bracket and press `shift+tab` (Press four times repeatedly to bring up detailed documentation)._

In [ ]:
# age

In [ ]:
# max heart rate

## Correlation matrices

---

A great way to easily get a feel for linear relationships between your variables is with a correlation matrix.

Below is the formula for the correlation between two variables $X$ and $Y$:

#### Correlation

### $$ \text{pearson correlation}\;r = cor(X, Y) =\frac{cov(X, Y)}{std(X)std(Y)}$$

#### The correlation matrix

We can see the correlation between all the numeric variables in our dataset by using the `.corr()` method.

It's useful to get a feel for which columns are correlated. The `.corr() method` can help you decide what is worth investigating further (though with a lot of variables, the matrix can be a bit overwhelming...)

In [ ]:
# A:

It can be difficult to spot any outliers simply by staring at our correlation matrix. To help get around this issue, let's use Seaborn's `.heatmap()` to give our correlation matrix some color.

In [ ]:
# A: